[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle wildcard subdomains
[[redirects]]
  from = "https://*:subdomain.myphd.site/*"
  to = "https://myphd.site/:splat"
  status = 200
  force = true

# Custom domain configuration
[context.production]
  base = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"